
export const COLORS = {
  green: '#1E6B52',
  orange: '#FF7A3D',
  white: '#FFFFFF',
  gray: '#F3F4F6',
  text: '#374151',
  border: '#E5E7EB'
};

export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar", "Blida", "Bouira",
  "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzو", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda",
  "Skikda", "Sidi Bel Abbès", "Annabba", "Guelma", "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara",
  "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arreridj", "Boumerدès", "El Tarf", "Tindouf", 
  "Tissemsilt", "El Oued", "Khenchela", "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
  "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal", "Béni Abbès", "In Salah", 
  "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Meniaa"
];

export type Language = 'ar' | 'fr' | 'en';

export const INTEREST_CATEGORIES = [
  { id: 'cars', label: 'سيارات ومركبات', emoji: '🚗' },
  { id: 'phones', label: 'هواتف ولوحات', emoji: '📱' },
  { id: 'computers', label: 'حواسيب وإعلام آلي', emoji: '💻' },
  { id: 'fashion', label: 'ملابس وأزياء', emoji: '👕' },
  { id: 'shoes', label: 'أحذية', emoji: '👟' },
  { id: 'livestock_sheep', label: 'أغنام ومواشي', emoji: '🐏' },
  { id: 'livestock_cow', label: 'أبقار وإنتاج حليبي', emoji: '🐄' },
  { id: 'realestate', label: 'عقارات وأراضي', emoji: '🏠' },
  { id: 'appliances', label: 'أجهزة كهرومنزلية', emoji: '📺' },
  { id: 'agriculture', label: 'معدات فلاحية', emoji: '🚜' },
  { id: 'construction', label: 'مواد بناء', emoji: '🏗️' },
  { id: 'sports', label: 'رياضة ولياقة', emoji: '⚽' },
  { id: 'beauty', label: 'تجميل وعناية', emoji: '✨' },
  { id: 'furniture', label: 'أثاث وديكور', emoji: '🛋️' }
];

export const TRANSLATIONS = {
  ar: {
    dir: 'rtl',
    brand: 'DZ MARKET',
    searchPlaceholder: 'واش راك تحوس اليوم في DZ MARKET؟',
    home: 'الرئيسية',
    notifications: 'الإشعارات',
    messages: 'الرسائل',
    heroTitle: 'تسوق بالهوية الجزائرية في DZ MARKET',
    heroBadge: 'سوق الجزائر المطور 🇩🇿',
    startShopping: 'ابدأ جولتك الآن',
    trending: '🔥 ترند الجزائر حالياً',
    backToShopping: 'الرئيسية',
    liveStream: 'بث مباشر للمنتجات',
    buyNow: 'اشتري الآن',
    totalPrice: 'المبلغ الإجمالي',
    specifications: 'تفاصيل المنتج',
    points: 'نقطة ولاء',
    logout: 'خروج',
    settings: 'الإعدادات',
    saveSettings: 'حفظ',
    saving: 'جاري الحفظ...',
    saved: 'تم بنجاح',
    followers: 'متابع',
    following: 'يتابع',
    posts: 'منشورات',
    myPosts: 'منشوراتي',
    savedItems: 'المحفوظات',
    platinumBuyer: 'مشتري VIP 💎',
    platinumSeller: 'بائع موثوق 💎',
    interestsTitle: 'وش هي اهتماماتك؟',
    interestsSubtitle: 'ساعدنا نخصص لك أفضل العروض في DZ MARKET.',
    continue: 'موافق',
    createPost: 'إنشاء منشور',
    postPlaceholder: 'واش راه في بالك اليوم؟ شارك تجربتك أو اعرض سلعتك...',
    publishPost: 'نشر المنشور',
    aiSuggest: 'اقتراح ذكي'
  },
  fr: {
    dir: 'ltr',
    brand: 'DZ MARKET',
    searchPlaceholder: 'Que cherchez-vous sur DZ MARKET ?',
    home: 'Accueil',
    notifications: 'Notifications',
    messages: 'Messages',
    heroTitle: 'Shopping algérien sur DZ MARKET',
    heroBadge: 'Le Smart Market d\'Algérie 🇩🇿',
    startShopping: 'Acheter maintenant',
    trending: '🔥 Tendances Actuelles',
    backToShopping: 'Retour',
    liveStream: 'Voir Live',
    buyNow: 'Acheter',
    totalPrice: 'Prix Total',
    specifications: 'Spécifications',
    points: 'points',
    logout: 'Quitter',
    settings: 'Paramètres',
    saveSettings: 'Enregistrer',
    saving: 'Enregistrement...',
    saved: 'Enregistré',
    followers: 'Abonnés',
    following: 'Abonnements',
    posts: 'Posts',
    myPosts: 'Mes Posts',
    savedItems: 'Favoris',
    platinumBuyer: 'Acheteur VIP 💎',
    platinumSeller: 'Vendeur Certifié 💎',
    interestsTitle: 'Vos Intérêts ?',
    interestsSubtitle: 'Personnalisez votre expérience DZ MARKET.',
    continue: 'Continuer',
    createPost: 'Créer un post',
    postPlaceholder: 'Quoi de neuf ? Partagez votre expérience...',
    publishPost: 'Publier',
    aiSuggest: 'Suggérer IA'
  },
  en: {
    dir: 'ltr',
    brand: 'DZ MARKET',
    searchPlaceholder: 'What are you looking for on DZ MARKET?',
    home: 'Home',
    notifications: 'Notifications',
    messages: 'Messages',
    heroTitle: 'Algerian Identity at DZ MARKET',
    heroBadge: 'Algeria\'s Smart Market 🇩🇿',
    startShopping: 'Start Shopping',
    trending: '🔥 Trending Now',
    backToShopping: 'Back',
    liveStream: 'Live Stream',
    buyNow: 'Buy Now',
    totalPrice: 'Total Price',
    specifications: 'Product Details',
    points: 'points',
    logout: 'Logout',
    settings: 'Settings',
    saveSettings: 'Save',
    saving: 'Saving...',
    saved: 'Saved',
    followers: 'Followers',
    following: 'Following',
    posts: 'Posts',
    myPosts: 'My Posts',
    savedItems: 'Saved',
    platinumBuyer: 'VIP Buyer 💎',
    platinumSeller: 'Trusted Seller 💎',
    interestsTitle: 'Your Interests?',
    interestsSubtitle: 'Personalize your DZ MARKET experience.',
    continue: 'Continue',
    createPost: 'Create Post',
    postPlaceholder: 'What\'s on your mind? Share your experience...',
    publishPost: 'Publish',
    aiSuggest: 'AI Suggest'
  }
};

export const MOCK_PRODUCTS: any[] = [
  {
    id: '1',
    name: 'سماعات DZ MARKET برو اللاسلكية',
    price: 8500,
    oldPrice: 12000,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80'
    ],
    rating: 4.9,
    reviewsCount: 312,
    sellerId: 's1',
    wilaya: 'الجزائر',
    isVerified: true,
    hasStudentDiscount: true,
    isFastDelivery: true,
    description: 'أفضل تجربة صوتية في الجزائر مع ميزة إلغاء الضوضاء وتصميم حصري لمنصة DZ MARKET.'
  },
  {
    id: '2',
    name: 'حذاء رياضي عصري',
    price: 4500,
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80'
    ],
    rating: 4.7,
    reviewsCount: 89,
    sellerId: 's2',
    wilaya: 'وهران',
    isVerified: true,
    hasStudentDiscount: false,
    isFastDelivery: true,
    description: 'حذاء رياضي يجمع بين الراحة والأناقة الجزائرية. مثالي للاستخدام اليومي والرياضي.'
  }
];
